version: '3.8'

services:
  web:
    build: .
    container_name: decabrina_web_production
    command: gunicorn decabrina.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.production
