# Generated by Django 5.2.2 on 2025-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='phone',
            field=models.CharField(blank=True, verbose_name='Номер'),
        ),
    ]
