# Generated by Django 5.2.1 on 2025-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0004_alter_customorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='comment_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='comment_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='dressmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dressmodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dressmodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='label_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='label_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='label_uz',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='textile',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textile',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textile',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
