# Generated by Django 5.2 on 2025-06-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0005_color_name_en_color_name_ru_color_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='size',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='size',
            name='label_uz',
        ),
    ]
