# Generated by Django 5.2 on 2025-06-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0006_remove_size_label_en_remove_size_label_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='phone',
        ),
    ]
