# Generated by Django 5.2.1 on 2025-06-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Размер товара', 'verbose_name_plural': 'Размеры товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_info',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image/products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='bust',
            field=models.CharField(max_length=20, verbose_name='Грудь'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='height',
            field=models.CharField(max_length=20, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='hips',
            field=models.CharField(max_length=20, verbose_name='Бёдра'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_label',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='waist',
            field=models.CharField(max_length=20, verbose_name='Талия'),
        ),
    ]
