# Generated by Django 5.2.2 on 2025-06-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='image/categories/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
