# Generated by Django 5.2.2 on 2025-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trends',
            field=models.BooleanField(default=False, verbose_name='В тренде'),
        ),
    ]
