# Generated by Django 5.2.1 on 2025-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_color_textile_product_colors_product_textiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_info_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_info_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_info_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='textile',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название ткани'),
        ),
        migrations.AddField(
            model_name='textile',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название ткани'),
        ),
        migrations.AddField(
            model_name='textile',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название ткани'),
        ),
    ]
