# Generated by Django 5.2 on 2025-06-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_info_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_info_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_info_uz',
        ),
    ]
